#!/usr/bin/with-contenv bash

if [ -z ${CONTAINER_IP} ]; then
    # If an IP wasn't given, assume the default route is the one to go for and get IP from that
    echo "CONTAINER_IP not set. Resolving from default route..."
    CONTAINER_IP=$(ip route get to 1.1.1.1 | awk '/1.1.1.1/ { print $7}')
fi

# Start dnsmasq
echo "Starting dnsmasq with DHCP_RANGE_START ${DHCP_RANGE_START} and CONTAINER_IP ${CONTAINER_IP}"
dnsmasq --no-daemon --dhcp-range=${DHCP_RANGE_START},proxy \
    --dhcp-boot=tag:bios,netboot.xyz.kpxe,,${CONTAINER_IP} \
    --dhcp-boot=tag:efi32,netboot.xyz.efi,,${CONTAINER_IP} \
    --dhcp-boot=tag:efi32-1,netboot.xyz.efi,,${CONTAINER_IP} \
    --dhcp-boot=tag:efi64,netboot.xyz.efi,,${CONTAINER_IP} \
    --dhcp-boot=tag:efi64-1,netboot.xyz.efi,,${CONTAINER_IP} \
    --dhcp-boot=tag:efi64-2,netboot.xyz.efi,,${CONTAINER_IP} \
    ${DNSMASQ_ARGS}
