---
name: Publish to Docker Hub
on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Publish master every Thursday at 7AM (schedule only applies to the master branch)
  schedule:
    - cron: "0 7 * * 4"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get datetime for tag
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DDTHHmmSS

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: latest,${{ steps.current-time.outputs.formattedTime }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}/dhcp-netboot.xyz
